import { AnyAction, ThunkDispatch } from '@reduxjs/toolkit'
import { DomainStrings, Portal, SideMenu } from 'interfaces'
import { Dispatch } from 'react'
import { NavigateFunction } from 'react-router-dom'
import {
  resetPortal,
  setPortal,
  setPortalPage,
} from 'utils/redux/slices/userInterfaceSlice'
import { RootState } from 'utils/redux/store'

/**
 * Builds the metadata for each link that renders in the Project Portal sidemenu.
 * @param userId
 * @returns {SideMenuInterface} Context for Project Portal sidemenu
 */
export const buildProjectPortalLinks = (projectId: string) => [
  {
    domain: 'project',
    headerTitle: 'Project Details',
    icon: 'description',
    label: 'Project Details',
    route: `/project/${projectId}`,
  },
  {
    domain: 'project',
    headerTitle: 'Team Members',
    icon: 'group',
    label: 'Team',
    route: `/project/${projectId}/team`,
  },
  {
    domain: 'project',
    headerTitle: 'Calendar',
    icon: 'calendar',
    label: 'Calendar',
    route: `/project/${projectId}/calendar`,
  },
  {
    domain: 'project',
    headerTitle: 'Task Management',
    icon: 'tasks',
    label: 'Task Management',
    route: `/project/${projectId}/tasks`,
  },
]

/**
 * Builds the metadata for each link that renders in the Settings sidemenu.
 * @param userId
 * @returns {SideMenuInterface} Context for Settings sidemenu
 */
export const buildSettingsPortalLinks = (userId: string) => [
  {
    domain: 'settings',
    icon: 'email',
    label: 'Email',
    route: `/users/${userId}/settings/email`,
  },
  {
    domain: 'settings',
    icon: 'lock',
    label: 'Password',
    route: `/users/${userId}/settings/password`,
  },
  {
    domain: 'settings',
    icon: 'account',
    label: 'Account',
    route: `/users/${userId}/settings/account`,
  },
]

/**
 * Builds the redux object for the Settings sidemenu.
 * @param projectId
 * @returns {SideMenuInterface} Context for settings sidemenu
 */
export const buildSettingsPortal = (userId: string) => {
  const portal: Portal = {
    active: true,
    type: 'settings',
  }

  const sideMenu: SideMenu = {
    active: true,
    links: buildSettingsPortalLinks(userId),
    title: 'Settings',
  }
  return { portal, sideMenu }
}

/**
 * Builds the redux object for the Project Portal sidemenu.
 * @param projectId
 * @returns {SideMenuInterface} Context for Project Portal sidemenu
 */
export const buildProjectPortal = (projectId: string) => {
  const portal: Portal = {
    active: true,
    headerTitle: 'Project Details',
    type: 'project',
  }

  const sideMenu: SideMenu = {
    active: true,
    links: buildProjectPortalLinks(projectId),
    title: 'Project Portal',
  }

  return { portal, sideMenu }
}

/**
 * Dispatches side menu state based on type of domain.
 * @param dispatch Instantiated dispatcher
 * @param domain Type of domain: "project" | "settings"
 * @param projectId
 */
export const buildPortal = (
  dispatch: ThunkDispatch<RootState, undefined, AnyAction> &
    Dispatch<AnyAction>,
  domain: DomainStrings,
  routeId: string
) => {
  if (domain === 'project') {
    dispatch(setPortal(buildProjectPortal(routeId)))
  } else if (domain === 'settings') {
    dispatch(setPortal(buildSettingsPortal(routeId)))
  } else {
    dispatch(resetPortal())
  }
}

export const changePortalPage = (dispatch, headerTitle) => {
  dispatch(setPortalPage(headerTitle))
}

/**
 * Checks if the current URL would belong to a menu link in the sidemenu
 * @returns The type of portal the URL belongs to.
 */
export const doesUrlBelongToPortal = (pathname, userId, projectId) => {
  if (buildSettingsPortalLinks(userId).find(link => link.route === pathname)) {
    return 'settings'
  } else if (
    buildProjectPortalLinks(projectId).find(link => link.route === pathname)
  ) {
    return 'project'
  } else return ''
}

/**
 * Looks for the menulink object the URL belongs to.
 * @returns The entire menu link object generated by the PortalLink builder.
 */
export const determinePortalFromUrl = (pathname, userId, projectId) => {
  if (pathname.includes('settings')) {
    return buildSettingsPortalLinks(userId).find(
      link => link.route === pathname
    )
  } else {
    return buildProjectPortalLinks(projectId).find(
      link => link.route === pathname
    )
  }
}

/**
 * Simply adds domain to Location state when routing user. Required for SideMenu usage.
 * @param navigate Callback returned from useNavigate()
 * @param route URL for user routing
 * @param domain Type of domain: "project" | "settings"
 */
export const navigateToDomain = (
  navigate: NavigateFunction,
  route: string,
  domain: DomainStrings
) => navigate(route, { state: { domain } })
