on: 
  pull_request:
    branches: ['development']

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checklist
        uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Repo    
        uses: actions/checkout@v3       
        with:
          Default: ${{ github.repository }}