name: Cypress Tests

on: push

env:
  CI: false

permissions:
  contents: write

jobs:
  cypress-run:
    environment:
      # name: ${{ contains(github.ref_name, 'release/')  && 'staging' || 'development'}}
      name: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: yeezick/bootcampr-backend
          token: ${{ secrets.GH_PAT }}
          path: backend
          ref: development
      - name: Run backend
        run: |
          cd backend && 
          npm install && 
          npm run dev & 
          sleep 5
        env:
          BACKEND_URL: http://localhost:8001
          FRONTEND_URL: http://localhost:3000
          TOKEN_KEY: ${{ vars.TOKEN_KEY }}
          MONGODB_URI: ${{ vars.MONGODB_URI }}
          CALENDAR_CREDS: ${{ vars.CALENDAR_CREDS }}
          CALENDAR_EMAIL: ${{ vars.CALENDAR_EMAIL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_EMAIL: ${{ vars.SENDGRID_EMAIL }}
          SENDGRID_ADMIN_EMAIL: ${{ vars.SENDGRID_ADMIN_EMAIL }}
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          path: frontend
      - name: Run frontend
        run: |
          cd frontend && 
          npm install && 
          npm run test:build &&
          npm run start &
          sleep 240
      - name: Checkout E2E suite
        uses: actions/checkout@v4
        with:
          repository: yeezick/collabify-qa
          token: ${{ secrets.GH_PAT }}
          path: e2e
          ref: ${{ github.ref_name  }}    
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run cy:run
          record: true
          wait-on: 'http://127.0.0.1:3000, http://127.0.0.1:8001'
          wait-on-timeout: 120
          working-directory: e2e/e2e-cypress
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
